version: '3'

services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    restart: always
    command: start --user root --pass Admin12$ file:/data/database.db
    ports:
      - 8000:8000
    volumes:
      - ./data:/data